use hoteldb;

insert into hotel (name, address, city, state, country, zipcode) VALUES ('Hilton hotel','1170 Spring St, Elizabeth','Newark','New Jersey','United States','07201');
insert into hotel (name, address, city, state, country, zipcode) VALUES ('Holiday Inn','585 8th Ave', 'New York','New York','United States','10018');
insert into hotel (name, address, city, state, country, zipcode) VALUES ('Governor hotel','86-90 Park Ln','London','','England','W1K 7TN');
insert into hotel (name, address, city, state, country, zipcode) VALUES ('New World hotel','72 Mody Rd, Tsim Sha Tsui','Hong Kong','','China','999077');
insert into hotel (name, address, city, state, country, zipcode) VALUES ('The Manila Hotel','1 Rizal Park','Manila','Metro Manila','Philippines','0913');

insert into room(roomNo, hotelNo, type, price) values (1,1,'Family',200);
insert into room(roomNo, hotelNo, type, price) values (2,1,'Family',200);
insert into room(roomNo, hotelNo, type, price) values (3,1,'Single',100);
insert into room(roomNo, hotelNo, type, price) values (4,1,'Single',100);
insert into room(roomNo, hotelNo, type, price) values (1,2,'Family',80);
insert into room(roomNo, hotelNo, type, price) values (2,2,'Family',85);
insert into room(roomNo, hotelNo, type, price) values (3,2,'Family',80);
insert into room(roomNo, hotelNo, type, price) values (1,3,'Single',35);
insert into room(roomNo, hotelNo, type, price) values (2,3,'Double',115);
insert into room(roomNo, hotelNo, type, price) values (3,3,'Double',115);
insert into room(roomNo, hotelNo, type, price) values (4,3,'Family',150);
insert into room(roomNo, hotelNo, type, price) values (1,4,'Single',30);
insert into room(roomNo, hotelNo, type, price) values (2,4,'Single',30);
insert into room(roomNo, hotelNo, type, price) values (3,4,'Single',30);
insert into room(roomNo, hotelNo, type, price) values (4,4,'Double',90);
insert into room(roomNo, hotelNo, type, price) values (5,4,'Double',90);
insert into room(roomNo, hotelNo, type, price) values (6,4,'Double',90);
insert into room(roomNo, hotelNo, type, price) values (7,4,'Family',110);
insert into room(roomNo, hotelNo, type, price) values (8,4,'Family',110);
insert into room(roomNo, hotelNo, type, price) values (1,5,'Double',38);
insert into room(roomNo, hotelNo, type, price) values (2,5,'Double',38);
insert into room(roomNo, hotelNo, type, price) values (3,5,'Single',32);
insert into room(roomNo, hotelNo, type, price) values (4,5,'Single',32);

insert into guest(name, address, city, state, country, zipcode) values ('John Doe','W 3rd St','Los Angeles','California','United States','90020');
insert into guest(name, address, city, state, country, zipcode) values ('Mary Jane','74 S 8th St','Brooklynn','New York','United States','11249');
insert into guest(name, address, city, state, country, zipcode) values ('Hank Kim','59 Arthur Rd','London','','United Kingdom','N7 6DT');
insert into guest(name, address, city, state, country, zipcode) values ('Bob Jones','143 Osbaldeston Rd','London','','United Kingdom','N16 6ND');
insert into guest(name, address, city, state, country, zipcode) values ('Paul John','65 Pitt St','New York','New York','United States','10002');
insert into guest(name, address, city, state, country, zipcode) values ('Ann Smith','32 Cliff St','New York','New York','United States','10038');
insert into guest(name, address, city, state, country, zipcode) values ('James Mann','21C Gayton Rd','London','','United Kingdom','NW3 1TY');
insert into guest(name, address, city, state, country, zipcode) values ('Mary Mann','42 Darenth Rd','London','','United Kingdom','N16 6EJ');
insert into guest(name, address, city, state, country, zipcode) values ('Jim Jones','545 Greenwich St','New York','New York','United States','10013');
insert into guest(name, address, city, state, country, zipcode) values ('Tom Jones','10600 Wilshire Blvd','Los Angeles','California','United States','90024');
insert into guest(name, address, city, state, country, zipcode) values ('Jimmy Johnson','63 Rutland St','Boston','Massachusetts','United States','02118');
insert into guest(name, address, city, state, country, zipcode) values ('Harry Coleman','3709 Park Ln','Dallas','Texas','United States','75220');
insert into guest(name, address, city, state, country, zipcode) values ('Bob James','939 Manning Ave','Los Angeles','California','United States','90024');
insert into guest(name, address, city, state, country, zipcode) values ('John Mary','39A Highbury Park','London','','United Kingdom','N5 1TH');
insert into guest(name, address, city, state, country, zipcode) values ('Jeff Bridges','13D Stavordale Rd','London','','United Kingdom','N5 1NE');
insert into guest(name, address, city, state, country, zipcode) values ('Larry Cohen','147 E 82nd St','New York','New York','United States','10028');

insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(1,1,'2021-09-05','2021-09-10',1);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(1,2,'2020-10-01','2020-10-04',2);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(1,3,'2020-10-01','2020-10-10',3);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(1,4,'2020-11-05','2020-11-20',4);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(2,5,'2020-11-05','2020-11-07',1);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(2,6,'2020-11-22','2020-11-29',2);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(3,7,'2021-09-08','2021-09-16',1);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(3,8,'2020-10-01','2020-10-10',2);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(4,9,'2021-09-05','2021-09-17',1);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(4,10,'2020-10-11','2020-10-18',2);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(5,11,'2020-11-11','2020-11-29',1);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(5,12,'2021-09-10','2021-09-11',3);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(5,13,'2021-01-10','2021-01-15',3);	
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(1,1,'2021-01-01','2021-01-12',2);	
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(1,15,'2021-01-02','2021-02-12',4);	
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(5,16,'2021-01-01','2021-01-12',2);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(2,5,'2021-01-15','2021-02-07',1);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(2,6,'2021-01-22','2021-02-15',3);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(3,7,'2021-02-08','2021-02-18',3);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(3,8,'2021-02-10','2021-02-19',4);