use hoteldb;

insert into hotel (name, address, city, stateCd, countryCd, zipCd) VALUES ('Hilton hotel','1170 Spring St, Elizabeth','Newark','NJ','US','07201');
insert into hotel (name, address, city, stateCd, countryCd, zipCd) VALUES ('Holiday Inn','585 8th Ave', 'New York','NY','US','10018');
insert into hotel (name, address, city, stateCd, countryCd, zipCd) VALUES ('Hilton Hawaiian Hotel','2005 Kālia Rd','Honolulu','HI','US','96815');
insert into hotel (name, address, city, stateCd, countryCd, zipCd) VALUES ('Caesars Palace','3570 S Las Vegas Blvd','Las Vegas','NV','US','89109');
insert into hotel (name, address, city, stateCd, countryCd, zipCd) VALUES ('Double Tree Hotel','128 Frontage Rd','Newark','NJ','US','07114');

insert into room(roomNo, hotelNo, type, price) values (1,1,'Family',200);
insert into room(roomNo, hotelNo, type, price) values (2,1,'Family',200);
insert into room(roomNo, hotelNo, type, price) values (3,1,'Single',100);
insert into room(roomNo, hotelNo, type, price) values (4,1,'Single',100);
insert into room(roomNo, hotelNo, type, price) values (1,2,'Family',80);
insert into room(roomNo, hotelNo, type, price) values (2,2,'Family',85);
insert into room(roomNo, hotelNo, type, price) values (3,2,'Family',80);
insert into room(roomNo, hotelNo, type, price) values (1,3,'Single',35);
insert into room(roomNo, hotelNo, type, price) values (2,3,'Double',115);
insert into room(roomNo, hotelNo, type, price) values (3,3,'Double',115);
insert into room(roomNo, hotelNo, type, price) values (4,3,'Family',150);
insert into room(roomNo, hotelNo, type, price) values (1,4,'Single',30);
insert into room(roomNo, hotelNo, type, price) values (2,4,'Single',30);
insert into room(roomNo, hotelNo, type, price) values (3,4,'Single',30);
insert into room(roomNo, hotelNo, type, price) values (4,4,'Double',90);
insert into room(roomNo, hotelNo, type, price) values (5,4,'Double',90);
insert into room(roomNo, hotelNo, type, price) values (6,4,'Double',90);
insert into room(roomNo, hotelNo, type, price) values (7,4,'Family',110);
insert into room(roomNo, hotelNo, type, price) values (8,4,'Family',110);
insert into room(roomNo, hotelNo, type, price) values (1,5,'Double',38);
insert into room(roomNo, hotelNo, type, price) values (2,5,'Double',38);
insert into room(roomNo, hotelNo, type, price) values (3,5,'Single',32);
insert into room(roomNo, hotelNo, type, price) values (4,5,'Single',32);

insert into guest(name, address, city, stateCd, countryCd, zipCd) values ('John Doe','W 3rd St','Los Angeles','CA','US','90020');
insert into guest(name, address, city, stateCd, countryCd, zipCd) values ('Mary Jane','74 S 8th St','Brooklynn','NY','US','11249');
insert into guest(name, address, city, stateCd, countryCd, zipCd) values ('Hank Kim','59 Arthur Rd','Irvine','CA','US','92122');
insert into guest(name, address, city, stateCd, countryCd, zipCd) values ('Bob Jones','143 River Rd','Santa Ana','CA','US','92020');
insert into guest(name, address, city, stateCd, countryCd, zipCd) values ('Paul John','65 Pitt St','New York','NY','US','10002');
insert into guest(name, address, city, stateCd, countryCd, zipCd) values ('Ann Smith','32 Cliff St','New York','NY','US','10038');
insert into guest(name, address, city, stateCd, countryCd, zipCd) values ('James Mann','21 Canyon Rd','San Diego','CA','US','91232');
insert into guest(name, address, city, stateCd, countryCd, zipCd) values ('Mary Mann','42 Ford Dr','San Diego','CA','US','93500');
insert into guest(name, address, city, stateCd, countryCd, zipCd) values ('Jim Jones','545 Greenwich St','New York','NY','US','10013');
insert into guest(name, address, city, stateCd, countryCd, zipCd) values ('Tom Jones','10600 Wilshire Blvd','Los Angeles','CA','US','90024');
insert into guest(name, address, city, stateCd, countryCd, zipCd) values ('Jimmy Johnson','63 Rutland St','Boston','MA','US','02118');
insert into guest(name, address, city, stateCd, countryCd, zipCd) values ('Harry Coleman','3709 Park Ln','Dallas','TX','US','75220');
insert into guest(name, address, city, stateCd, countryCd, zipCd) values ('Bob James','939 Manning Ave','Los Angeles','CA','US','90024');
insert into guest(name, address, city, stateCd, countryCd, zipCd) values ('John Mary','39A Highbury Park','New York','NY','US','10010');
insert into guest(name, address, city, stateCd, countryCd, zipCd) values ('Jeff Bridges','13D Stavordale Rd','New York','NY','US','10015');
insert into guest(name, address, city, stateCd, countryCd, zipCd) values ('Larry Cohen','147 E 82nd St','New York','NY','US','10028');

insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(1,1,'2021-09-05','2021-09-10',1);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(1,2,'2020-10-01','2020-10-04',2);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(1,3,'2020-10-01','2020-10-10',3);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(1,4,'2020-11-05','2020-11-20',4);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(2,5,'2020-11-05','2020-11-07',1);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(2,6,'2020-11-22','2020-11-29',2);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(3,7,'2021-09-08','2021-09-16',1);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(3,8,'2020-10-01','2020-10-10',2);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(4,9,'2021-09-05','2021-09-17',1);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(4,10,'2020-10-11','2020-10-18',2);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(5,11,'2020-11-11','2020-11-29',1);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(5,12,'2021-09-10','2021-09-11',3);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(5,13,'2021-01-10','2021-01-15',3);	
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(1,1,'2021-01-01','2021-01-12',2);	
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(1,15,'2021-01-02','2021-02-12',4);	
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(5,16,'2021-01-01','2021-01-12',2);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(2,5,'2021-01-15','2021-02-07',1);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(2,6,'2021-01-22','2021-02-15',3);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(3,7,'2021-02-08','2021-02-18',3);
insert into booking(hotelNo, guestNo, dateFrom, dateTo, roomNo) values(3,8,'2021-02-10','2021-02-19',4);